const SET_USER_INFO = 'SET_USER_INFO';
const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS';
const SET_PAGE_USER_INFO = 'SET_PAGE_USER_INFO';
const SET_PAGE_POSTS = 'SET_PAGE_POSTS';
const ADD_PAGE_POSTS = 'ADD_PAGE_POSTS';
const SET_EDITOR_STATE = 'SET_EDITOR_STATE';
const RESET_EDITOR_STATE = 'RESET_EDITOR_STATE';

export {
  SET_USER_INFO,
  SET_NOTIFICATIONS,
  ADD_NOTIFICATIONS,
  SET_PAGE_USER_INFO,
  SET_PAGE_POSTS,
  ADD_PAGE_POSTS,
  SET_EDITOR_STATE,
  RESET_EDITOR_STATE,
};
